### ISSUE TITLE
latest release looks like has git conflict markers still in 

### ISSUE THREAD

**Issue by barnabym** [idexo/idexo-sdk#2]
/Users/barnabymenage/proj_idexo_drupal/code_idexo_drupal/node_modules/idexo-sdk/index.js:24
<<<<<<< HEAD
^^

SyntaxError: Unexpected token '<<'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/barnabymenage/proj_idexo_drupal/code_idexo_drupal/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

**Comment by marleymarl** [comment]
thank you - latest update 7.5 fixes the issue
